FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install 

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN bun run db:generate
RUN bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun", "run", "start:web"]