FROM oven/bun:1.3.10 

WORKDIR /app

# Copy workspace manifests first for better layer caching
COPY package.json bun.lock ./
COPY apps/backend/package.json apps/backend/package.json
COPY packages/db/package.json packages/db/package.json

# Install all workspace deps (needed because backend uses "db": "*")
RUN bun install --frozen-lockfile


# Copy source
COPY apps/backend apps/backend
COPY packages/db packages/db

EXPOSE 8080

CMD ["bun", "run", "index.ts"]