FROM oven/bun:1

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run generate:db
RUN DB_URL=$DATABASE_URL bunx turbo build --filter=web...

EXPOSE 3000

# Start the frontend application
CMD ["bun", "start:frontend"]